import type { GuideFaqItem, GuideLink } from "./sequence-guides";

export interface GeneratorAbout {
  slug: string;
  eyebrow: string;
  title: string;
  description: string;
  intro: string;
  body: string[];
  features: string[];
  links: GuideLink[];
}

export interface GeneratorFaq {
  slug: string;
  eyebrow: string;
  title: string;
  description: string;
  intro: string;
  items: GuideFaqItem[];
  links: GuideLink[];
}

const sharedToolLinks: GuideLink[] = [
  { href: "/tools/sequence-generator", label: "Sequence Generator" },
  { href: "/tools/tiktok-comment", label: "TikTok Comment" },
];

export const generatorAbouts: Record<string, GeneratorAbout> = {
  hub: {
    slug: "about",
    eyebrow: "About",
    title: "About Generator Hub",
    description:
      "Learn about Generator Hub's mission, technology, and team. Free generators for TikTok comments, math sequences, and ETL guidance.",
    intro:
      "Generator Hub builds lightweight, privacy-first generator tools that work in the browser. No accounts, no data storage, just useful output.",
    body: [
      "Generator Hub is a compact collection of web-based generators built for content creators, developers, and data engineers. Every tool runs directly in your browser or via one-off server requests. We never store your input or results on the server.",
      "The site is built with React 19, Tailwind CSS 4, and deployed on Cloudflare Workers for fast global delivery. It uses Vinext for server-side rendering, ensuring search engines and AI crawlers can understand every page without running JavaScript.",
      "We design for simplicity. Each tool does one thing well. Each guide page is structured for scanning. Everything loads fast and works on mobile.",
    ],
    features: [
      "TikTok Comment Generator - AI-powered grouped replies with tone and goal controls",
      "Sequence Generator - Arithmetic, geometric, Fibonacci, random, and formula-based sequences with chart and CSV export",
      "ETL Sequence Guides - Informatica, IICS, Snowflake, and conceptual references",
      "Privacy-first: no cookies, no tracking, no data storage",
      "Open source friendly structure with structured data and llms.txt",
    ],
    links: [
      ...sharedToolLinks,
      { href: "/sequence-generator-meaning", label: "Sequence Generator Meaning" },
    ],
  },
  "tiktok-comment": {
    slug: "tools/tiktok-comment/about",
    eyebrow: "About",
    title: "About TikTok Comment Generator",
    description:
      "How the TikTok Comment Generator works, its AI model, privacy guarantees, and ideal use cases.",
    intro:
      "The TikTok Comment Generator creates authentic, grouped comments from your video context, target language, tone, and goals.",
    body: [
      "Describe your TikTok video with a short caption, add optional keywords or hashtags, pick a language and tone, and select comment goals. The generator returns grouped comments organized by intent - praise, humor, debate starter, and more.",
      "Comments are generated by an AI language model via a one-off server request. Your input is sent to the model, processed, and the result is returned. No input or output is stored on the server. Generated comments are filtered for duplicates and unsafe content before appearing in your browser.",
      "Ideal for content creators who need quick comment drafts, social media managers running engagement campaigns, and anyone who wants to preview how different tones sound under a video.",
    ],
    features: [
      "10 comment goals including Max Likes, Genuine Insight, Debate Starter, and more",
      "15 supported languages with natively-written comments",
      "8 tone styles from Funny/Meme to Professional/Thoughtful",
      "Grouped output with 1-click copy per group or per comment",
      "Export all generated comments as a .txt file",
    ],
    links: [
      { href: "/tools/sequence-generator", label: "Sequence Generator" },
    ],
  },
  "bible-verse": {
    slug: "tools/bible-verse/about",
    eyebrow: "About",
    title: "About Bible Verse Generator",
    description:
      "Learn about the Bible Verse Generator, its translations, spiritual moods, and how it helps with daily reflection.",
    intro:
      "The Bible Verse Generator is a free tool for daily spiritual reflection, offering verses based on your mood across multiple translations.",
    body: [
      "Select a spiritual mood—such as Anxious, Grateful, Seeking, or Confused—and receive a carefully curated Bible verse to guide your reflection. The tool supports multiple translations including the King James Version (KJV), World English Bible (WEB), and Bible in Basic English (BBE).",
      "Designed for a distraction-free experience, the generator features both a bright minimal mode and a dark meditative mode with ambient glowing effects, helping you focus entirely on the Word.",
      "All verses are generated instantly in your browser. There is no account required, and your selections remain private to your device."
    ],
    features: [
      "Curated verses categorized by 6 spiritual moods",
      "3 supported Bible translations (KJV, WEB, BBE)",
      "Distraction-free meditative dark mode",
      "One-click verse copying with reference formatting",
      "Instantly generated with no server-side tracking"
    ],
    links: [
      { href: "/tools/sequence-generator", label: "Sequence Generator" },
    ],
  },
  "sequence-generator": {
    slug: "tools/sequence-generator/about",
    eyebrow: "About",
    title: "About Sequence Generator",
    description:
      "How the Sequence Generator works, its five math modes, chart and CSV export, and privacy.",
    intro:
      "Sequence Generator is a free browser-based tool for creating arithmetic, geometric, Fibonacci, random, and formula-based number sequences.",
    body: [
      "Pick a mode, set your parameters, and generate a sorted list of terms. Every calculation runs in your browser - nothing is sent to a server. You can view terms as a list, copy individual values, export to CSV, or view a lightweight SVG chart of the sequence.",
      "The tool supports five generation modes: arithmetic (constant difference), geometric (constant ratio), Fibonacci (recurrence), random (bounded values), and formula (custom expression with variable n). Start and diff/ratio/range fields adapt to the selected mode.",
      "Designed for math students, teachers, data analysts, and developers who need quick test data or want to explore numeric patterns without installing software.",
    ],
    features: [
      "Five sequence modes: Arithmetic, Geometric, Fibonacci, Random, Formula",
      "Configurable term count from 1 to 200",
      "Inline SVG chart visualizing the sequence curve",
      "CSV export for use in spreadsheets and data tools",
      "Copy individual terms or the entire sequence",
      "All calculations run client-side for instant results",
    ],
    links: [
      { href: "/tools/tiktok-comment", label: "TikTok Comment" },
      { href: "/tools/sequence-generator/faq", label: "Sequence Generator FAQ" },
      { href: "/sequence-generator-meaning", label: "Sequence Generator Meaning" },
    ],
  },
  "informatica-sequence-generator": {
    slug: "informatica-sequence-generator/about",
    eyebrow: "About",
    title: "About the Informatica Guide",
    description:
      "Purpose and scope of the Informatica Sequence Generator guide - who it is for and what it covers.",
    intro:
      "This guide page explains the Informatica PowerCenter Sequence Generator transformation for data engineers and ETL developers.",
    body: [
      "The guide covers the core transformation behavior, NEXTVAL and CURRVAL ports, basic flow setup, and common surrogate key patterns. It is written for practitioners who need a quick reference rather than full product documentation.",
      "The content focuses on mapping-level usage inside PowerCenter. It does not cover installation, licensing, or cloud migration topics. For IICS specifics, see the dedicated IICS guide.",
    ],
    features: [
      "What It Does section covering the three core behaviors",
      "Core Ports table mapping element, meaning, and typical use",
      "Basic Flow step-by-step setup walkthrough",
      "Typical surrogate-key pattern code example",
      "FAQ covering CURRVAL usage and source key alternatives",
    ],
    links: [
      { href: "/informatica-sequence-generator-config", label: "Configuration Guide" },
      { href: "/iics-sequence-generator", label: "IICS Sequence Generator" },
      { href: "/informatica-sequence-generator/faq", label: "Informatica FAQ" },
    ],
  },
  "informatica-sequence-generator-config": {
    slug: "informatica-sequence-generator-config/about",
    eyebrow: "About",
    title: "About the Config Guide",
    description:
      "Purpose and scope of the Informatica Sequence Generator configuration guide.",
    intro:
      "This guide covers configuration priorities for the Informatica Sequence Generator: start values, increment rules, and restart behavior.",
    body: [
      "Most configuration problems trace back to start values, increment settings, or restart expectations. This guide walks through each setting with a risk assessment for misconfiguration, then provides a safe configuration sequence with a pre-load target check SQL snippet.",
      "Written for ETL developers who already understand the basic transformation but need configuration-specific guidance.",
    ],
    features: [
      "Config Priorities section with three core configuration areas",
      "Settings to Check table with verification guidance and risk assessment",
      "Safe Configuration Sequence step-by-step instructions",
      "Pre-load target check SQL code example",
      "FAQ on cycle mode and value gaps after restart",
    ],
    links: [
      { href: "/informatica-sequence-generator", label: "Informatica Basics" },
      { href: "/snowflake-sequence-generator", label: "Snowflake Guide" },
      { href: "/informatica-sequence-generator-config/faq", label: "Config FAQ" },
    ],
  },
  "iics-sequence-generator": {
    slug: "iics-sequence-generator/about",
    eyebrow: "About",
    title: "About the IICS Guide",
    description:
      "Purpose and scope of the IICS Sequence Generator guide.",
    intro:
      "This guide explains how Sequence Generator works in Informatica Intelligent Cloud Services and how it differs from PowerCenter.",
    body: [
      "The guide covers IICS-specific differences, a comparison table versus PowerCenter, a typical cloud mapping setup walkthrough, and a simple mapping flow code example. FAQ items address when to use IICS generator vs database sequences.",
      "Written for cloud ETL developers who need to generate surrogate keys inside IICS mapping tasks.",
    ],
    features: [
      "Key Differences section with three cloud-specific points",
      "IICS vs PowerCenter comparison table",
      "Typical Mapping Setup step-by-step",
      "Simple cloud mapping flow code example",
      "FAQ on database sequence alternatives",
    ],
    links: [
      { href: "/informatica-sequence-generator", label: "PowerCenter Basics" },
      { href: "/snowflake-sequence-generator", label: "Snowflake Comparison" },
      { href: "/iics-sequence-generator/faq", label: "IICS FAQ" },
    ],
  },
  "snowflake-sequence-generator": {
    slug: "snowflake-sequence-generator/about",
    eyebrow: "About",
    title: "About the Snowflake Guide",
    description:
      "Purpose and scope of the Snowflake Sequence Generator guide.",
    intro:
      "This guide covers Snowflake SEQUENCE objects, NEXTVAL usage, and warehouse-owned key generation patterns.",
    body: [
      "Snowflake sequences are database objects, not ETL transformations. This guide covers when to use them, important syntax, a warehouse-owned key flow, and a create-and-use SQL code example. FAQ items explain sequence value gaps and ownership conflicts.",
      "Written for data engineers and Snowflake users who need to generate unique numeric IDs at the database layer.",
    ],
    features: [
      "When to Use It section with three decision points",
      "Important Syntax table for CREATE, NEXTVAL, and ALTER",
      "Warehouse-Owned Key Flow step-by-step",
      "Create and use a sequence SQL code example",
      "FAQ on value gaps and ownership conflicts",
    ],
    links: [
      { href: "/informatica-sequence-generator", label: "Informatica Comparison" },
      { href: "/iics-sequence-generator", label: "IICS Guide" },
      { href: "/snowflake-sequence-generator/faq", label: "Snowflake FAQ" },
    ],
  },
  "sequence-generator-meaning": {
    slug: "sequence-generator-meaning/about",
    eyebrow: "About",
    title: "About the Meaning Guide",
    description:
      "Purpose and scope of the Sequence Generator Meaning guide covering math, ETL, and digital electronics contexts.",
    intro:
      "This guide clarifies the shared term 'sequence generator' across math tools, ETL software, and digital electronics.",
    body: [
      "The term causes confusion because it appears in drastically different contexts. This guide presents three common meanings, a decision table mapping context to best starting point, a quick decision path, and code examples for math-style and ETL-style references. A digital electronics diagram illustrates the hardware perspective.",
      "Written for anyone searching 'sequence generator' who needs to know which tool or guide matches their actual need.",
    ],
    features: [
      "Three Common Meanings section covering math, ETL, and electronics",
      "Which One Do You Need decision table",
      "Quick Decision Path for rapid context matching",
      "Math-style and ETL-style code examples",
      "Digital electronics diagram illustrating state transitions",
      "FAQ on calculator vs mechanism confusion",
    ],
    links: [
      { href: "/tools/sequence-generator", label: "Try the Math Tool" },
      { href: "/sequence-generator-meaning/faq", label: "Meaning FAQ" },
    ],
  },
};

export const generatorFaqs: Record<string, GeneratorFaq> = {
  hub: {
    slug: "faq",
    eyebrow: "FAQ",
    title: "Frequently Asked Questions",
    description:
      "Common questions about Generator Hub, its tools, privacy policy, and technology.",
    intro:
      "Find answers to common questions about Generator Hub's tools, privacy, and technology.",
    items: [
      {
        question: "Is Generator Hub free to use?",
        answer: "Yes. All tools and guides on Generator Hub are completely free with no usage limits or paid tiers.",
      },
      {
        question: "Do you store my data?",
        answer: "No. Generator Hub does not use cookies, tracking, or server-side data storage. TikTok Comment input is sent to an AI model for generation but is not retained after the request completes. Sequence Generator runs entirely in your browser with no server communication.",
      },
      {
        question: "How does the TikTok Comment Generator work?",
        answer: "You provide a video caption, select a language and tone, and choose comment goals. The input is sent to an AI language model which returns grouped comments. The generator filters duplicates and unsafe content before displaying results.",
      },
      {
        question: "What sequence modes are available?",
        answer: "The Sequence Generator supports arithmetic (constant difference), geometric (constant ratio), Fibonacci (recurrence), random (bounded values), and formula (custom expression using variable n) modes.",
      },
      {
        question: "Can I use the generated content commercially?",
        answer: "Yes. Output from Generator Hub tools can be used for any purpose, including commercial projects. No attribution is required.",
      },
      {
        question: "How do I report an issue or suggest a feature?",
        answer: "Currently the best way is through open-source channels or direct contact at contact@generators.317713.xyz.",
      },
    ],
    links: sharedToolLinks,
  },
  "tiktok-comment": {
    slug: "tools/tiktok-comment/faq",
    eyebrow: "FAQ",
    title: "TikTok Comment FAQ",
    description:
      "Frequently asked questions about the TikTok Comment Generator - tone, language, goals, privacy, and usage tips.",
    intro:
      "Find answers to common questions about generating TikTok comments with tone control, language support, and goal selection.",
    items: [
      {
        question: "How many comments does the generator produce?",
        answer: "The generator returns grouped comments organized by your selected goals (up to 2). Each group typically contains 3-5 comments. The total count depends on your goals and caption length.",
      },
      {
        question: "What languages are supported?",
        answer: "14 languages are supported: English, Chinese (Simplified and Traditional), Japanese, Korean, Thai, Russian, Spanish, Portuguese, French, German, Indonesian, Hindi, Vietnamese, and Arabic. Comments are generated natively in the selected language.",
      },
      {
        question: "What does each comment goal produce?",
        answer: "Max Likes aims for broadly engaging comments. Max Replies provokes response chains. Debate Starter creates respectful contrasting viewpoints. Praise/Hype generates enthusiastic support. Humor focuses on funny, relatable takes. Genuine Insight provides thoughtful analysis.",
      },
      {
        question: "Can I regenerate comments for the same input?",
        answer: "Yes. Click the generate button again and you will get a fresh set of comments. The AI model produces different output each time.",
      },
      {
        question: "How long should my caption be?",
        answer: "Aim for 20-200 characters describing the video context. Longer captions give the AI more material to work with, but very short captions still produce useful results.",
      },
      {
        question: "Are the comments safe and appropriate?",
        answer: "The generator filters unsafe content, slurs, personal attacks, and hate speech. Debate Starter comments are designed to be respectful and non-abusive. However, AI-generated content should always be reviewed before posting.",
      },
    ],
    links: [
      { href: "/tools/sequence-generator", label: "Sequence Generator" },
    ],
  },
  "bible-verse": {
    slug: "tools/bible-verse/faq",
    eyebrow: "FAQ",
    title: "Bible Verse FAQ",
    description:
      "Frequently asked questions about the Bible Verse Generator, translations, and meditative mode.",
    intro:
      "Find answers to common questions about generating verses, switching translations, and using the meditative mode.",
    items: [
      {
        question: "Which Bible translations are supported?",
        answer: "Currently, the tool supports the King James Version (KJV), World English Bible (WEB), and the Bible in Basic English (BBE). You can toggle between them using the selector at the top.",
      },
      {
        question: "How are the verses selected?",
        answer: "Verses are curated into specific spiritual moods (like Anxious, Grateful, or Seeking). When you generate a verse, the tool randomly selects one from the category that matches your current mood.",
      },
      {
        question: "What is meditative mode?",
        answer: "Meditative mode is a distraction-free dark theme with ambient visual effects, designed to help you focus and reflect on the Scripture in a peaceful digital environment.",
      },
      {
        question: "Can I copy the verses?",
        answer: "Yes, each generated verse comes with a 'Copy' button that copies both the text and the biblical reference directly to your clipboard.",
      },
      {
        question: "Do I need an account to save verses?",
        answer: "No account is required. The tool is designed for quick, ephemeral daily reflection rather than long-term storage, ensuring complete privacy.",
      },
    ],
    links: [
      { href: "/tools/tiktok-comment", label: "TikTok Comment" },
    ],
  },
  "sequence-generator": {
    slug: "tools/sequence-generator/faq",
    eyebrow: "FAQ",
    title: "Sequence Generator FAQ",
    description:
      "Frequently asked questions about Sequence Generator modes, formulas, CSV export, and chart features.",
    intro:
      "Find answers to common questions about generating number sequences, using formulas, and exporting results.",
    items: [
      {
        question: "What is the difference between arithmetic and geometric sequences?",
        answer: "Arithmetic sequences add a constant difference between terms (e.g. 2, 5, 8, 11 with diff=3). Geometric sequences multiply by a constant ratio (e.g. 2, 6, 18, 54 with ratio=3).",
      },
      {
        question: "How does the formula mode work?",
        answer: "Enter a JavaScript expression using the variable n (starting from 0). For example, '2 * n + 1' generates 1, 3, 5, 7 and 'Math.pow(2, n)' generates 1, 2, 4, 8. Only safe math functions and operators are allowed.",
      },
      {
        question: "What is the maximum number of terms I can generate?",
        answer: "Up to 200 terms. The tool validates that values stay within safe numeric bounds and blocks non-finite or oversized results.",
      },
      {
        question: "Can I export the sequence to Excel?",
        answer: "Yes. Use the CSV export button to download a .csv file. The first column is the index (1-based) and the second column is the term value. This file opens directly in Excel, Google Sheets, or any spreadsheet tool.",
      },
      {
        question: "How does the chart work?",
        answer: "The chart is an inline SVG that plots each term's value against its index (position in the sequence). It updates instantly when you generate a new sequence. For large sequences (100+ terms), the chart shows the overall trend while keeping individual points visible.",
      },
      {
        question: "Is my sequence data sent to a server?",
        answer: "No. All calculations run entirely in your browser using JavaScript. No data is sent to any server. This means results appear instantly with no network latency.",
      },
    ],
    links: [
      { href: "/tools/sequence-generator/about", label: "About Sequence Generator" },
      { href: "/tools/tiktok-comment", label: "TikTok Comment" },
      { href: "/sequence-generator-meaning", label: "Sequence Generator Meaning" },
    ],
  },
  "informatica-sequence-generator": {
    slug: "informatica-sequence-generator/faq",
    eyebrow: "FAQ",
    title: "Informatica Sequence Generator FAQ",
    description:
      "Extended FAQ for Informatica Sequence Generator - advanced questions not covered in the main guide.",
    intro:
      "Additional frequently asked questions about Informatica Sequence Generator beyond the main guide page.",
    items: [
      {
        question: "Can I use multiple Sequence Generator transformations in one mapping?",
        answer: "Yes. Use a separate Sequence Generator for each target table that needs independent surrogate key ranges. Make sure each generator has a distinct start value range to prevent key collisions.",
      },
      {
        question: "What happens to sequence values when a session fails?",
        answer: "Sequence Generator does not roll back values after failures. Gaps appear in the target key range because the generator advanced past the failed rows. Use the config guide's restart flow to realign start values after recovery.",
      },
      {
        question: "Does Sequence Generator work with CDC or incremental loads?",
        answer: "Yes. It generates unique values regardless of load type. For CDC, make sure the generator runs in the same mapping path as the target insert. For incremental loads, set the start value above the existing maximum key.",
      },
      {
        question: "Can Sequence Generator produce non-numeric values?",
        answer: "No. Sequence Generator outputs integer values only. For string-based keys, use an Expression transformation to concatenate a prefix with the generated number.",
      },
    ],
    links: [
      { href: "/informatica-sequence-generator", label: "Main Guide" },
      { href: "/informatica-sequence-generator-config", label: "Configuration Guide" },
      { href: "/informatica-sequence-generator/about", label: "About This Guide" },
    ],
  },
  "informatica-sequence-generator-config": {
    slug: "informatica-sequence-generator-config/faq",
    eyebrow: "FAQ",
    title: "Informatica Config FAQ",
    description:
      "Extended FAQ for Informatica Sequence Generator configuration - advanced setup questions.",
    intro:
      "Additional frequently asked questions about configuring the Informatica Sequence Generator beyond the main config guide page.",
    items: [
      {
        question: "How do I handle multi-partition sessions with Sequence Generator?",
        answer: "Use increment by equal to the partition count and offset each partition's start value. For 4 partitions with increment=4: partition 1 starts at 1, partition 2 at 2, partition 3 at 3, partition 4 at 4. This guarantees unique keys without collisions.",
      },
      {
        question: "What is the recommended restart strategy for daily batch loads?",
        answer: "Before each load, query the target table's maximum key, add a safety margin (e.g. +1000), and set that as the start value. This handles failed loads and makes retries safe. Document the procedure so operators can repeat it consistently.",
      },
      {
        question: "Can end value be used for range enforcement?",
        answer: "End value is rarely needed for surrogate keys. It stops the generator after reaching a maximum, which can cause load failures if the range is exhausted. Leave it at the default unless you have a documented reason to cap key ranges.",
      },
    ],
    links: [
      { href: "/informatica-sequence-generator-config", label: "Main Config Guide" },
      { href: "/informatica-sequence-generator", label: "Informatica Basics" },
      { href: "/informatica-sequence-generator-config/about", label: "About This Guide" },
    ],
  },
  "iics-sequence-generator": {
    slug: "iics-sequence-generator/faq",
    eyebrow: "FAQ",
    title: "IICS Sequence Generator FAQ",
    description:
      "Extended FAQ for IICS Sequence Generator - cloud-specific questions.",
    intro:
      "Additional frequently asked questions about Sequence Generator in Informatica Intelligent Cloud Services.",
    items: [
      {
        question: "How does IICS Sequence Generator handle concurrent task runs?",
        answer: "Each task instance maintains its own sequence state. For concurrent runs writing to the same target, use database-native sequences instead of the ETL-side generator to prevent key collisions between parallel processes.",
      },
      {
        question: "Can I use Sequence Generator in a Data Integration mapping template?",
        answer: "Yes. Sequence Generator works inside mapping templates the same way as in individual mappings. The generated values are scoped to each template instance execution.",
      },
      {
        question: "What happens to sequence state when a mapping task is paused and resumed?",
        answer: "The sequence continues from its last emitted value. No values are skipped during a clean pause-resume cycle. Unclean interruptions (task crashes) follow the same gap behavior as PowerCenter.",
      },
    ],
    links: [
      { href: "/iics-sequence-generator", label: "Main Guide" },
      { href: "/informatica-sequence-generator", label: "PowerCenter Basics" },
      { href: "/iics-sequence-generator/about", label: "About This Guide" },
    ],
  },
  "snowflake-sequence-generator": {
    slug: "snowflake-sequence-generator/faq",
    eyebrow: "FAQ",
    title: "Snowflake Sequence FAQ",
    description:
      "Extended FAQ for Snowflake SEQUENCE objects - usage, gaps, permissions, and performance.",
    intro:
      "Additional frequently asked questions about Snowflake SEQUENCE objects beyond the main guide page.",
    items: [
      {
        question: "What permissions are needed to use a sequence?",
        answer: "To call NEXTVAL, you need USAGE privilege on the sequence. To create or alter a sequence, you need CREATE SEQUENCE or ownership on the schema. Sequences inherit schema-level grants like other schema objects.",
      },
      {
        question: "How does sequence caching work in Snowflake?",
        answer: "Snowflake caches sequence values by default (cache size 20). This improves performance for high-frequency NEXTVAL calls. Cached values are lost on server restart, creating larger gaps. Set NO CACHE for gap-minimized sequences at the cost of performance.",
      },
      {
        question: "Can I reset a sequence to a specific value?",
        answer: "Use ALTER SEQUENCE seq_name SET VALUE = n to reset. The next NEXTVAL call returns n + increment. Alternatively, CREATE OR REPLACE the sequence with a new START value to fully reset it.",
      },
      {
        question: "Are sequences transaction-safe?",
        answer: "NEXTVAL calls are not transactional. Once a value is consumed, it is never reissued, even if the transaction rolls back. This guarantees uniqueness at the cost of potential gaps.",
      },
    ],
    links: [
      { href: "/snowflake-sequence-generator", label: "Main Guide" },
      { href: "/informatica-sequence-generator", label: "Informatica Comparison" },
      { href: "/snowflake-sequence-generator/about", label: "About This Guide" },
    ],
  },
  "sequence-generator-meaning": {
    slug: "sequence-generator-meaning/faq",
    eyebrow: "FAQ",
    title: "Sequence Generator Meaning FAQ",
    description:
      "Extended FAQ about the term sequence generator across math, ETL, and electronics contexts.",
    intro:
      "Additional questions about the meaning and context of 'sequence generator' across different fields.",
    items: [
      {
        question: "How do I explain the difference to a non-technical person?",
        answer: "Think of it like a counter with rules. In math, it is a list of numbers following a pattern. In ETL, it is a tool that assigns unique IDs to database rows. In electronics, it is a circuit that cycles through states on a timer.",
      },
      {
        question: "Are sequence generators in ETL and Snowflake the same concept?",
        answer: "They serve the same purpose (generating unique numeric identifiers) but operate at different layers. ETL generators run inside the data pipeline tool. Snowflake sequences run inside the database. Best practice: pick one layer as the single source of truth for keys.",
      },
      {
        question: "What is a state machine sequence generator?",
        answer: "In digital electronics, a sequence generator is a finite state machine that cycles through predetermined states. Each clock pulse advances to the next state. Common examples include counters (0,1,2,3...) and pseudo-random pattern generators used in testing.",
      },
    ],
    links: [
      { href: "/sequence-generator-meaning", label: "Main Guide" },
      { href: "/tools/sequence-generator", label: "Try the Math Tool" },
      { href: "/sequence-generator-meaning/about", label: "About This Guide" },
    ],
  },
};

export function getGeneratorAbout(slug: string): GeneratorAbout {
  return generatorAbouts[slug];
}

export function getGeneratorFaq(slug: string): GeneratorFaq {
  return generatorFaqs[slug];
}
